Game.class: Game.java Knight.class Rook.class Bishop.class King.class Queen.class Pawn.class Player1.class Player2.class 
	javac Game.java

Knight.class: Piece.java Knight.java
	javac Knight.java
Rook.class: Rook.java Piece.java
	javac Rook.java
Bishop.class: Bishop.java Piece.java
	javac Bishop.java
King.class: King.java Piece.java
	javac King.java
Queen.class: Queen.java Piece.java
	javac Queen.java
Pawn.class: Pawn.java Piece.java
	javac Pawn.java
Player1.class: Player1.java Player.java
	javac Player1.java
Player2.class: Player2.java Player.java
	javac Player2.java
run: Game.class
	java Game
clean:
	rm *.class

